logging:
  level:
    com.sslproxy.coordinator: DEBUG
    com.zaxxer.hikari: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari.pool.HikariPool: DEBUG
    oracle.jdbc: INFO
    oracle.jdbc.driver: INFO
    oracle.ucp: INFO
    oracle.ucp.jdbc: INFO
    org.apache.camel.component.jdbc: DEBUG
    org.apache.camel.component.sql: DEBUG
    org.postgresql: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG
    org.springframework.orm.jpa: DEBUG
