-- ============================================================================
-- TiDB schema for coordinator Oracle → TiDB migration
-- Database: coordinator
-- Target:  TiDB (MySQL-compatible)
--
-- Translated from Oracle DDLs in apps/schema-migrator/sql/oracle/core/03_tables/
--
-- Notable Oracle→TiDB changes:
--   VARCHAR2(n)          → VARCHAR(n) CHARACTER SET utf8mb4
--   NUMBER(p,s)          → INT / BIGINT / DECIMAL(p,s) / TINYINT
--   RAW(16)              → BINARY(16)
--   TIMESTAMP WITH TIME ZONE → TIMESTAMP(6)  (TiDB stores as UTC internally)
--   SYSTIMESTAMP         → CURRENT_TIMESTAMP(6)
--   SYS_EXTRACT_UTC(...) → UTC_TIMESTAMP(6)
--   GENERATED ALWAYS AS IDENTITY → AUTO_INCREMENT
--   GENERATED ALWAYS AS (...) VIRTUAL → removed (TiDB limitation)
--   BLOCKCHAIN TABLE     → regular table
--   NO DROP / NO DELETE LOCKED / HASHING → removed
--   PARTITION BY RANGE ... INTERVAL → removed (single-node dev)
--   RELY DISABLE NOVALIDATE → removed
--   NVL()                → IFNULL()
--   FROM DUAL            → FROM DUAL (MySQL supports it)
-- ============================================================================

CREATE DATABASE IF NOT EXISTS coordinator
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE coordinator;

-- --------------------------------------------------------------------------
-- 1. PROXY_EVENTS
-- --------------------------------------------------------------------------
CREATE TABLE PROXY_EVENTS (
    ID                   BIGINT       NOT NULL AUTO_INCREMENT,
    BATCH_ID             VARCHAR(36)  NOT NULL,
    ROW_SEQUENCE         INT          NOT NULL,
    EVENT_TIME           TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    EVENT_TIMESTAMP_UTC  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    EVENT_TYPE           VARCHAR(32)  NOT NULL,
    HOST                 VARCHAR(253) NOT NULL,
    PEER_IP              VARCHAR(45)  DEFAULT NULL,
    WG_PUBKEY            VARCHAR(64)  DEFAULT NULL,
    DEVICE_ID            BINARY(16)   DEFAULT NULL,
    IDENTITY_SOURCE      VARCHAR(16)  DEFAULT 'unknown',
    PEER_HOSTNAME        VARCHAR(253) DEFAULT NULL,
    CLIENT_UA            VARCHAR(512) DEFAULT NULL,
    BYTES_UP             BIGINT       DEFAULT 0,
    BYTES_DOWN           BIGINT       DEFAULT 0,
    STATUS_CODE          INT          DEFAULT NULL,
    BLOCKED              TINYINT(1)   DEFAULT 0,
    OBFUSCATION_PROFILE  VARCHAR(32)  DEFAULT NULL,
    CORRELATION_ID       BINARY(16)   DEFAULT NULL,
    PARENT_EVENT_ID      BIGINT       DEFAULT NULL,
    EVENT_SEQUENCE       INT          DEFAULT NULL,
    DURATION_MS          BIGINT       DEFAULT NULL,
    REASON               VARCHAR(64)  DEFAULT NULL,
    RAW_JSON             JSON         DEFAULT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY PROXY_EVENTS_BATCH_ROW_IDX (BATCH_ID, ROW_SEQUENCE),
    KEY PROXY_EVENTS_EVENT_UTC_IDX (EVENT_TIMESTAMP_UTC),
    KEY PROXY_EVENTS_TIME_IDX (EVENT_TIME DESC),
    KEY PROXY_EVENTS_HOST_IDX (HOST, EVENT_TIME),
    KEY PROXY_EVENTS_BLOCKED_IDX (BLOCKED, EVENT_TIME DESC),
    KEY PROXY_EVENTS_DEVICE_TIME_IDX (DEVICE_ID, EVENT_TIME DESC),
    KEY PROXY_EVENTS_WG_PUBKEY_TIME_IDX (WG_PUBKEY, EVENT_TIME DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------------------------
-- 2. PROXY_BLOCKED_HOST_ROLLUPS
-- --------------------------------------------------------------------------
CREATE TABLE PROXY_BLOCKED_HOST_ROLLUPS (
    ID                 BIGINT       NOT NULL AUTO_INCREMENT,
    HOST               VARCHAR(253) NOT NULL,
    BLOCKED_ATTEMPTS   BIGINT       DEFAULT 0 NOT NULL,
    BLOCKED_BYTES      BIGINT       DEFAULT 0 NOT NULL,
    FREQUENCY_HZ       DECIMAL(10,4) DEFAULT 0 NOT NULL,
    VERDICT            VARCHAR(32)  NOT NULL,
    CATEGORY           VARCHAR(64)  DEFAULT NULL,
    RISK_SCORE         DECIMAL(10,4) DEFAULT 0,
    TARPIT_HELD_MS     BIGINT       DEFAULT 0,
    IAT_MS             BIGINT       DEFAULT NULL,
    CONSECUTIVE_BLOCKS INT          DEFAULT 0,
    LAST_VERDICT       VARCHAR(32)  DEFAULT NULL,
    TLS_VER            VARCHAR(16)  DEFAULT NULL,
    ALPN               VARCHAR(64)  DEFAULT NULL,
    JA3_LITE           VARCHAR(512) DEFAULT NULL,
    RESOLVED_IP        VARCHAR(45)  DEFAULT NULL,
    ASN_ORG            VARCHAR(128) DEFAULT NULL,
    UPDATED_AT         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    FIRST_SEEN         TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    UNIQUE KEY PROXY_BLOCKED_HOST_UQ (HOST),
    KEY PROXY_BLOCKED_UPDATED_IDX (UPDATED_AT DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------------------------
-- 3. PROXY_PAYLOAD_AUDIT
-- Note: Oracle used BLOCKCHAIN TABLE with HASHING. TiDB has no equivalent.
--       This is a regular table.
-- --------------------------------------------------------------------------
CREATE TABLE PROXY_PAYLOAD_AUDIT (
    ID                 BIGINT       NOT NULL AUTO_INCREMENT,
    CORRELATION_ID     BINARY(16)   NOT NULL,
    HOST               VARCHAR(253) NOT NULL,
    DIRECTION          VARCHAR(4)   NOT NULL COMMENT 'UP or DOWN',
    CAPTURED_AT        DATETIME(6)  NOT NULL,
    BYTE_OFFSET        INT          DEFAULT 0 NOT NULL,
    PAYLOAD_OBJECT_KEY VARCHAR(512) DEFAULT NULL,
    CONTENT_TYPE       VARCHAR(128) DEFAULT NULL,
    HTTP_METHOD        VARCHAR(16)  DEFAULT NULL,
    HTTP_STATUS        INT          DEFAULT NULL,
    HTTP_PATH          VARCHAR(1024) DEFAULT NULL,
    IS_ENCRYPTED       TINYINT(1)   DEFAULT 0 NOT NULL,
    TRUNCATED          TINYINT(1)   DEFAULT 0 NOT NULL,
    PEER_IP            VARCHAR(45)  DEFAULT NULL,
    NOTES              VARCHAR(512) DEFAULT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY PROXY_PAYLOAD_AUDIT_UQ (CORRELATION_ID, HOST, DIRECTION, CAPTURED_AT, BYTE_OFFSET),
    KEY PROXY_PAYLOAD_CORR_IDX (CORRELATION_ID),
    KEY PROXY_PAYLOAD_HOST_IDX (HOST, CAPTURED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------------------------
-- 4. WIRELESS_SENSORS
-- --------------------------------------------------------------------------
CREATE TABLE WIRELESS_SENSORS (
    SENSOR_PK     BIGINT       NOT NULL AUTO_INCREMENT,
    SENSOR_ID     VARCHAR(64)  NOT NULL,
    LOCATION_ID   VARCHAR(128) NOT NULL,
    INTERFACE     VARCHAR(32)  NOT NULL,
    REG_DOMAIN    VARCHAR(8)   DEFAULT NULL,
    FIRST_SEEN_AT TIMESTAMP(6) NOT NULL,
    LAST_SEEN_AT  TIMESTAMP(6) NOT NULL,
    CREATED_AT    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (SENSOR_PK),
    UNIQUE KEY WIRELESS_SENSORS_ID_UQ (SENSOR_ID),
    KEY WIRELESS_SENSORS_LOCATION_IDX (LOCATION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------------------------
-- 5. WIRELESS_AUDIT_FRAMES
-- Note: Oracle virtual column OBSERVED_UTC_DATE removed.
--       Oracle FK to WIRELESS_CHANNELS removed (table not migrated).
-- --------------------------------------------------------------------------
CREATE TABLE WIRELESS_AUDIT_FRAMES (
    FRAME_PK          BIGINT       NOT NULL AUTO_INCREMENT,
    BATCH_ID          VARCHAR(128) NOT NULL,
    ROW_SEQUENCE      INT          NOT NULL,
    EVENT_TYPE        VARCHAR(64)  NOT NULL,
    OBSERVED_AT       TIMESTAMP(6) NOT NULL,
    SENSOR_ID         VARCHAR(64)  NOT NULL,
    LOCATION_ID       VARCHAR(128) NOT NULL,
    INTERFACE         VARCHAR(32)  NOT NULL,
    CHANNEL           SMALLINT     NOT NULL,
    BAND              VARCHAR(8)   NOT NULL,
    FRAME_TYPE        VARCHAR(32)  DEFAULT NULL,
    FRAME_SUBTYPE     VARCHAR(32)  NOT NULL,
    BSSID             VARCHAR(17)  DEFAULT NULL,
    SOURCE_MAC        VARCHAR(17)  DEFAULT NULL,
    DESTINATION_MAC   VARCHAR(17)  DEFAULT NULL,
    TRANSMITTER_MAC   VARCHAR(17)  DEFAULT NULL,
    RECEIVER_MAC      VARCHAR(17)  DEFAULT NULL,
    DESTINATION_BSSID VARCHAR(17)  DEFAULT NULL,
    SSID              VARCHAR(256) DEFAULT NULL,
    SIGNAL_DBM        SMALLINT     DEFAULT NULL,
    SEQUENCE_NUMBER   INT          DEFAULT NULL,
    RAW_LEN           INT          NOT NULL,
    IS_RETRY          TINYINT(1)   DEFAULT 0 NOT NULL,
    IS_MORE_DATA      TINYINT(1)   DEFAULT 0 NOT NULL,
    IS_POWER_SAVE     TINYINT(1)   DEFAULT 0 NOT NULL,
    IS_PROTECTED      TINYINT(1)   DEFAULT 0 NOT NULL,
    IS_TO_DS          TINYINT(1)   DEFAULT 0 NOT NULL,
    IS_FROM_DS        TINYINT(1)   DEFAULT 0 NOT NULL,
    IS_HANDSHAKE      TINYINT(1)   DEFAULT 0 NOT NULL,
    SECURITY_FLAGS    INT          DEFAULT 0 NOT NULL,
    DEVICE_ID         VARCHAR(128) DEFAULT NULL,
    USERNAME          VARCHAR(256) DEFAULT NULL,
    IDENTITY_SOURCE   VARCHAR(64)  DEFAULT 'unknown' NOT NULL,
    TAGS              VARCHAR(2000) DEFAULT NULL,
    ANOMALY_REASONS   VARCHAR(1000) DEFAULT NULL,
    RAW_JSON          JSON         DEFAULT NULL,
    CREATED_AT        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (FRAME_PK),
    UNIQUE KEY WIRELESS_AUDIT_FRAMES_BATCH_UQ (BATCH_ID, ROW_SEQUENCE),
    KEY WIRELESS_FRAMES_SENSOR_TIME_IDX (SENSOR_ID, OBSERVED_AT),
    KEY WIRELESS_FRAMES_LOCATION_TIME_IDX (LOCATION_ID, OBSERVED_AT),
    KEY WIRELESS_FRAMES_SOURCE_MAC_IDX (SOURCE_MAC, OBSERVED_AT),
    KEY WIRELESS_FRAMES_BSSID_IDX (BSSID, OBSERVED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------------------------
-- 6. WIRELESS_BANDWIDTH_WINDOWS
-- Note: Oracle virtual column WINDOW_START_UTC_DATE removed.
--       Oracle FK to WIRELESS_CHANNELS removed.
-- --------------------------------------------------------------------------
CREATE TABLE WIRELESS_BANDWIDTH_WINDOWS (
    BW_PK                BIGINT       NOT NULL AUTO_INCREMENT,
    BATCH_ID             VARCHAR(128) NOT NULL,
    ROW_SEQUENCE         INT          NOT NULL,
    SCHEMA_VERSION       SMALLINT     DEFAULT 1 NOT NULL,
    WINDOW_START         TIMESTAMP(6) NOT NULL,
    WINDOW_END           TIMESTAMP(6) NOT NULL,
    SENSOR_ID            VARCHAR(64)  NOT NULL,
    LOCATION_ID          VARCHAR(128) NOT NULL,
    INTERFACE            VARCHAR(32)  NOT NULL,
    CHANNEL              SMALLINT     NOT NULL,
    BAND                 VARCHAR(8)   NOT NULL,
    SOURCE_MAC           VARCHAR(17)  NOT NULL,
    DESTINATION_BSSID    VARCHAR(17)  NOT NULL,
    SSID                 VARCHAR(256) DEFAULT NULL,
    BYTES                BIGINT       DEFAULT 0 NOT NULL,
    FRAME_COUNT          BIGINT       DEFAULT 0 NOT NULL,
    RETRY_COUNT          BIGINT       DEFAULT 0 NOT NULL,
    MORE_DATA_COUNT      BIGINT       DEFAULT 0 NOT NULL,
    POWER_SAVE_COUNT     BIGINT       DEFAULT 0 NOT NULL,
    STRONGEST_SIGNAL_DBM SMALLINT     DEFAULT NULL,
    HIST_UNDER_100       BIGINT       DEFAULT 0 NOT NULL,
    HIST_100_500         BIGINT       DEFAULT 0 NOT NULL,
    HIST_500_1000        BIGINT       DEFAULT 0 NOT NULL,
    HIST_1000_1500       BIGINT       DEFAULT 0 NOT NULL,
    INTER_ARRIVAL_P50_MS INT          DEFAULT NULL,
    EXTERNAL_BSSID       TINYINT(1)   DEFAULT 0 NOT NULL,
    THRESHOLD_EXCEEDED   TINYINT(1)   DEFAULT 0 NOT NULL,
    WALL_CLOCK_DELTA_MS  BIGINT       DEFAULT NULL,
    WINDOW_IS_PARTIAL    TINYINT(1)   DEFAULT 0 NOT NULL,
    PUBLISHED_AT         TIMESTAMP(6) DEFAULT NULL,
    CREATED_AT           TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (BW_PK),
    UNIQUE KEY WIRELESS_BW_WINDOWS_BATCH_UQ (BATCH_ID, ROW_SEQUENCE),
    KEY WIRELESS_BW_SENSOR_TIME_IDX (SENSOR_ID, WINDOW_START),
    KEY WIRELESS_BW_THRESHOLD_IDX (THRESHOLD_EXCEEDED, WINDOW_START),
    KEY WIRELESS_BW_SOURCE_MAC_IDX (SOURCE_MAC, WINDOW_START),
    -- TiDB requires tidb_enable_check_constraint=ON to enforce this CK;
    -- set in session or cluster config if runtime validation is needed.
    CONSTRAINT WIRELESS_BW_WINDOWS_RANGE_CK CHECK (WINDOW_END >= WINDOW_START)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------------------------
-- 7. WIRELESS_ALERTS
-- Note: Oracle virtual column DETECTED_UTC_DATE removed.
--       Oracle unique index used NVL() for nullable columns — TiDB allows
--       multiple NULLs in unique indexes, so the simple composite index works.
-- --------------------------------------------------------------------------
CREATE TABLE WIRELESS_ALERTS (
    ALERT_PK        BIGINT       NOT NULL AUTO_INCREMENT,
    ALERT_TYPE      VARCHAR(64)  NOT NULL,
    BATCH_ID        VARCHAR(128) DEFAULT NULL,
    ROW_SEQUENCE    INT          DEFAULT NULL,
    ALERT_DATE      DATE         DEFAULT NULL,
    DETECTED_AT     TIMESTAMP(6) NOT NULL,
    SENSOR_ID       VARCHAR(64)  NOT NULL,
    LOCATION_ID     VARCHAR(128) NOT NULL,
    INTERFACE       VARCHAR(32)  DEFAULT NULL,
    CHANNEL         SMALLINT     DEFAULT NULL,
    PRIMARY_MAC     VARCHAR(17)  DEFAULT NULL,
    SECONDARY_MAC   VARCHAR(17)  DEFAULT NULL,
    SSID            VARCHAR(256) DEFAULT NULL,
    SIGNAL_DBM      SMALLINT     DEFAULT NULL,
    BYTES           BIGINT       DEFAULT NULL,
    DETAILS_JSON    JSON         DEFAULT NULL,
    RAW_JSON        JSON         DEFAULT NULL,
    ACKNOWLEDGED    TINYINT(1)   DEFAULT 0 NOT NULL,
    ACKNOWLEDGED_BY VARCHAR(128) DEFAULT NULL,
    ACKNOWLEDGED_AT TIMESTAMP(6) DEFAULT NULL,
    CREATED_AT      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UPDATED_AT      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ALERT_PK),
    UNIQUE KEY WIRELESS_ALERTS_BATCH_UQ (ALERT_TYPE, BATCH_ID, ROW_SEQUENCE),
    KEY WIRELESS_ALERTS_TYPE_TIME_IDX (ALERT_TYPE, DETECTED_AT DESC),
    KEY WIRELESS_ALERTS_SENSOR_TIME_IDX (SENSOR_ID, DETECTED_AT DESC),
    KEY WIRELESS_ALERTS_UNACK_IDX (ACKNOWLEDGED, DETECTED_AT DESC),
    KEY WIRELESS_BW_ALERT_DAY_IDX (ALERT_TYPE, SENSOR_ID, PRIMARY_MAC, SECONDARY_MAC, ALERT_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------------------------
-- 8. WIRELESS_ALERTS_LEDGER
-- Note: Oracle used BLOCKCHAIN TABLE with HASHING. TiDB has no equivalent.
--       This is a regular table.
-- --------------------------------------------------------------------------
CREATE TABLE WIRELESS_ALERTS_LEDGER (
    LEDGER_ID      BIGINT       NOT NULL AUTO_INCREMENT,
    ALERT_PK       BIGINT       NOT NULL,
    ALERT_TYPE     VARCHAR(64)  NOT NULL,
    BATCH_ID       VARCHAR(128) DEFAULT NULL,
    ROW_SEQUENCE   INT          DEFAULT NULL,
    ALERT_DATE     DATE         DEFAULT NULL,
    DETECTED_AT    TIMESTAMP(6) NOT NULL,
    SENSOR_ID      VARCHAR(64)  NOT NULL,
    LOCATION_ID    VARCHAR(128) NOT NULL,
    INTERFACE      VARCHAR(32)  DEFAULT NULL,
    CHANNEL        SMALLINT     DEFAULT NULL,
    PRIMARY_MAC    VARCHAR(17)  DEFAULT NULL,
    SECONDARY_MAC  VARCHAR(17)  DEFAULT NULL,
    SSID           VARCHAR(256) DEFAULT NULL,
    SIGNAL_DBM     SMALLINT     DEFAULT NULL,
    BYTES          BIGINT       DEFAULT NULL,
    DETAILS_JSON   JSON         DEFAULT NULL,
    RAW_JSON       JSON         DEFAULT NULL,
    ACKNOWLEDGED   TINYINT(1)   NOT NULL,
    LEDGER_ACTION  VARCHAR(16)  NOT NULL,
    CAPTURED_AT    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (LEDGER_ID),
    KEY WIRELESS_ALERTS_LEDGER_ALERT_IDX (ALERT_PK, CAPTURED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------------------------
-- 9. WIRELESS_CLIENT_INVENTORY
-- Note: Oracle unique index used SYS_EXTRACT_UTC(SNAPSHOT_AT) expression.
--       TiDB does not support expression indexes. The Java code should pass
--       SNAPSHOT_AT as UTC for the unique constraint to work correctly.
-- --------------------------------------------------------------------------
CREATE TABLE WIRELESS_CLIENT_INVENTORY (
    INVENTORY_PK    BIGINT       NOT NULL AUTO_INCREMENT,
    SENSOR_ID       VARCHAR(64)  NOT NULL,
    LOCATION_ID     VARCHAR(128) NOT NULL,
    SNAPSHOT_AT     TIMESTAMP(6) NOT NULL,
    CLIENT_MAC      VARCHAR(17)  NOT NULL,
    BSSID           VARCHAR(17)  DEFAULT NULL,
    SSID            VARCHAR(256) DEFAULT NULL,
    DEVICE_ID       VARCHAR(128) DEFAULT NULL,
    USERNAME        VARCHAR(256) DEFAULT NULL,
    IDENTITY_SOURCE VARCHAR(64)  DEFAULT NULL,
    LAST_SEEN       TIMESTAMP(6) NOT NULL,
    FIRST_SEEN      TIMESTAMP(6) NOT NULL,
    SIGNAL_DBM      SMALLINT     DEFAULT NULL,
    IS_AUTHORIZED   TINYINT(1)   DEFAULT 0 NOT NULL,
    CREATED_AT      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (INVENTORY_PK),
    UNIQUE KEY WIRELESS_CLIENT_INV_UQ (SENSOR_ID, SNAPSHOT_AT, CLIENT_MAC),
    KEY WIRELESS_INV_SENSOR_SNAP_IDX (SENSOR_ID, SNAPSHOT_AT),
    KEY WIRELESS_INV_CLIENT_MAC_IDX (CLIENT_MAC, SNAPSHOT_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------------------------
-- 10. WIRELESS_PROBE_REQUESTS
-- --------------------------------------------------------------------------
CREATE TABLE WIRELESS_PROBE_REQUESTS (
    PROBE_PK    BIGINT       NOT NULL AUTO_INCREMENT,
    BATCH_ID    VARCHAR(128) NOT NULL,
    CLIENT_MAC  VARCHAR(17)  NOT NULL,
    SSID        VARCHAR(256) NOT NULL,
    KNOWN_BSSID VARCHAR(17)  DEFAULT NULL,
    FIRST_SEEN  TIMESTAMP(6) NOT NULL,
    LAST_SEEN   TIMESTAMP(6) NOT NULL,
    PROBE_COUNT INT          DEFAULT 1 NOT NULL,
    CREATED_AT  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (PROBE_PK),
    UNIQUE KEY WIRELESS_PROBE_BATCH_UQ (BATCH_ID, CLIENT_MAC, SSID),
    KEY WIRELESS_PROBES_CLIENT_MAC_IDX (CLIENT_MAC, LAST_SEEN),
    KEY WIRELESS_PROBES_SSID_IDX (SSID, LAST_SEEN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;